### ISSUE TITLE
ERROR: Service 'web' failed to build : Build failed

### ISSUE THREAD

**Issue by umutcaptain** [realsuayip/django-sozluk#100]
Step 7/21 : COPY ../requirements.txt .
COPY failed: forbidden path outside the build context: ../requirements.txt ()
ERROR: Service 'web' failed to build : Build failed

Şuayip hocam merhabalar,

Babam için, sizin kodlamış olduğunuz sözlüğünüzü çok fazla docker tecrübem olmaması dolayısıyla kendi başıma yapmaya çalışıyorum.

Not : daha önce jitsi docker kurulumunu başarı ile gerçekleştirmiştim.

/django-sozluk-1.5.1# docker-compose -f docker/docker-compose.yml up -d

komutumdan sonra aldığım hata yukarıdaki gibidir.

Vaktinizden çaldığım için özür diler, yardımlarınızı beklerim.

Kolaylıklar.

uMut

**Comment by realsuayip** [comment]
selamlar, docker yapılandırmanız ile ilgili bir hata gibi duruyor. working directory yanlış olabilir gibi sanki?
