### ISSUE TITLE
Veritabanı portunu localhost'a açık yapmak

### ISSUE THREAD

**Issue by sadhorse79** [realsuayip/django-sozluk#105]
öğrendiğim kadarıyla 5432 olan veritabanı portu yalnızca o docker üzerinde çalışıyor. bunu localhost'a açıp kendi node.js uygulamamın da bağlanmasını istiyorum. 
nasıl olur? teşekkürler.

**Comment by realsuayip** [comment]
compose'da postgres servisine

```yaml
    ports:
      - "5432:5432"
```

eklerseniz 5432 portundan container içindeki postgrese erişebilir localhostta çalışan node js appiniz.

tabii benim tavsiyem node js appinizi de docker compose içine almanız.
