### ISSUE TITLE
kurulumdan sonra linkler 404 hatası veriyor.

### ISSUE THREAD

**Issue by kadirgecit** [realsuayip/django-sozluk#11]
cloudlinux kernel ile cpanel üzerine kurulum yaptım ve gereklilikleri yükledim anasayfa çalışıyor sadece ancak linklerin tamamında 404 hatası alıyorum yardımcı olur musunuz

**Comment by realsuayip** [comment]
selamlar, developer toolsdan linklerin nereye yönlendirdiğine bakabilir misiniz? örneğin sağ üstteki giriş yap linki'nin hedefi '/login/' olmalı. manuel olarak adres satırınıa yazdığınızda, örneğin hostname/login/ girilebiliyor mu? eğer girilemiyorsa, debug modu açıkken 404 ile ilgili info verir orada ne yazıyor?

**Comment by techmasterz** [comment]
![Ekran görüntüsü 2021-12-31 134539](https://user-images.githubusercontent.com/66552942/147819112-828f32a2-6daa-49e9-8bdf-8d4e39d4f648.png)

**Comment by techmasterz** [comment]
Bunun hakkında yardım talep ediyorum.
