### ISSUE TITLE
operationalerror hatasını alıyorum

### ISSUE THREAD

**Issue by halitartuc** [realsuayip/django-sozluk#12]
Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.2.13
OperationalError
no such table: django_site
C:\Users\Halit\Desktop\dj\venv\lib\site-packages\django\db\backends\sqlite3\base.py in execute, line 383
C:\Users\Halit\Desktop\dj\venv\Scripts\python.exe
3.8.3
['C:\\Users\\Halit\\Desktop\\dj',  'C:\\Users\\Halit\\Desktop\\dj\\venv\\Scripts\\python38.zip',  'c:\\users\\halit\\appdata\\local\\programs\\python\\python38-32\\DLLs',  'c:\\users\\halit\\appdata\\local\\programs\\python\\python38-32\\lib',  'c:\\users\\halit\\appdata\\local\\programs\\python\\python38-32',  'C:\\Users\\Halit\\Desktop\\dj\\venv',  'C:\\Users\\Halit\\Desktop\\dj\\venv\\lib\\site-packages']
Paz, 28 Haz 2020 14:35:56 +0300

bu hatayı alıyorum nasıl çözüceğimi bilmiyorum yardımcı olur musun?

**Comment by realsuayip** [comment]
selamlar, ilk kurulumda bu komutları çalıştırıp, tabloları hazır hale getirmeniz gerekiyordu bu adımı atladınız büyük ihtimalle.

(venv'de)
`python manage.py makemigrations`
`python manage.py migrate`

https://docs.djangoproject.com/en/3.0/topics/migrations/#workflow

**Comment by halitartuc** [comment]
djangoda yeniyim tam bilmiyorum kurulumu nası yapacağımı biraz anlatabilir misiniz ? her defasında hata alıyorum sqllite'da dahil doğru düzgün birşeyi yapamadım ve çalışmanızı görmek istiyorum şimdiden teşekkür ederim :)

**Comment by halitartuc** [comment]
makemigrations'u çalıştırdığımda no changes detected diyor bu yüzden yeni başladım djangoya ve çözemedim kusura bakmayın lütfen

**Comment by realsuayip** [comment]
Dosyaları fetch ettikten sonra ana dizinde iken bir virtual environment oluşturmanız gerekiyor. Bunu nasıl yapacağınızı Google'da çok rahat bulabilirsiniz. Gereksinimleri yükledikten sonra yukarıda belirttiğim kodları çalıştırmanız gerekiyor.

Eğer database'i oluşturamıyor iseniz migrations klasörünü ve db.sqlite dosyasını silip bahsettiğim kodları tekrar çalıştırın, bana Telegram'da aynı kullanıcı adımla ulaşabilirsin.
