### ISSUE TITLE
More comprehensive tests required

### ISSUE THREAD

**Issue by realsuayip** [realsuayip/django-sozluk#2]
I included the first tests of this repository in 2e4151b34e524e6a838b2905fb9bcf6f4cbb1840 which are related to Author model (this was actually the first time I wrote tests).

Of course this project needs tons of more tests, so If you have some ideas or in experienced in testing, your help would be appreciated.

**Comment by JackKilby** [comment]
forward it to me i can test it for you

**Comment by JackKilby** [comment]
hey man notice me when you re online i wanna talk with you

**Comment by JackKilby** [comment]
heyyyyyy im gonna sleep in 2 hours please reply

**Comment by realsuayip** [comment]
> hey man notice me when you re online i wanna talk with you

Hey bro, you can e-mail me or you can find me on Facebook, my username is the same (realsuayip).

**Comment by JackKilby** [comment]
facebook kullanan mı kaldı amk

**Comment by JackKilby** [comment]
man do you have instagram?
we can do it in there or e-mail me SikichiBoY1996pomPa@hotmail.com

**Comment by JackKilby** [comment]
it looks weird but i created in 2008 so don t judge me

**Comment by kralbay** [comment]
@realsuayip Merhaba Şuayip, Sözlük scriptinizi inceledim. Oldukça güzel yazılmış ellerinize sağlık.
Whatsapp, skype veya mail adresinizi alabilir miyim.
Mevcutta bir sözlük sitesi yönetiyorum. 
Bu scriptinizi ücretli bir şekilde geliştirilip kullanmak istiyorum.
Eğer eksikleri hakkında benim için geliştirme yapabilirseniz (ücreti) mukabilinde görüşmek istiyorum.
Cevabınızı sabırsızlıkla bekliyorum.
kralbay@gmail.com mailden bana ulaşabilirsiniz.

**Comment by fatihtoptas** [comment]
i will help about that.

**Comment by techmasterz** [comment]
I have really important information about site, please read your message box in sozluk.me

**Comment by EchoBilisim** [comment]
Merhaba yazılımı çok beğendim ellerinize sağlık böyle güzel yazılımları gördükçe biz türkleri bir daha taktir ediyorum böyle güzel yazılımları ücretsiz sunması ve bir beklentisi olmadan güncellemesi güzel bişey başarılar diliyorum.

Bu yazılımı bende kullanmak istiyorum ancak bu tür kurulumlarda biraz geride kaldım pek bilgim olmuyor php yazlımları veya hazır yazılımları kurmaktan yana sıkıntı yaşamıyorum ancak böyle bu tür kurulumlar her zaman beni aşıyor kurulumda bana yardımcı olursanız çok sevinirim bu güzel yazılımı kullanmak isterim şimdiden teşekkürlerimi sunarım başarıların devamını dilerim.
