### ISSUE TITLE
admin panelinden kanal eklenen başlıklar, bugün bölümünden kayboluyor. 

### ISSUE THREAD

**Issue by fatihtoptas** [realsuayip/django-sozluk#21]
yeni açılmış bir başlık olsa bile, admin bölümünden kanal belirtirsek, başlık yalnızca o kanal içerisinde görünüyor ve bugünden kayboluyor.

**Comment by fatihtoptas** [comment]
anladığım kadarıyla, bugün kısmında yalnızca kanalsız olanların görünmesi sağlanmış. aslında öyle olmamalı diye düşünüyorum.

**Comment by realsuayip** [comment]
bugün'de takip etmediğiniz kanallara ait başlıklar görünmez, kanallar listesine bakıp hangi kanalları takip ediyorsunuz görebilirsiniz.
