### ISSUE TITLE
Admin paneline girilemiyor

### ISSUE THREAD

**Issue by cakmakfurkan** [realsuayip/django-sozluk#23]
1.1 sürümünde /admin e gidildiğinde log in ekranına yönlendiriyor. Admin hesabıyla giriş yaptıktan sonra da ana ekrana yönlendiriyor. Tekrar admin paneline giriş yapmak istenirse aynı adımlar tekrar ediyor hiçbir şekilde admin paneline erişim sağlanamıyor.

**Comment by realsuayip** [comment]
selamlar, admin hesabı createsuperuser komutuyla oluşturulur. GENERIC_SUPERUSER_USERNAME ile belirttiğiniz kişi admin olmaz, hakiki admin hesabı ile giriş yaptığınız zaman /admin dizinine erişebilirsiniz.

**Comment by cakmakfurkan** [comment]
Teşekkürler, Docker build işlemi gerçekleşirken birkaç hata aldım. 2-3 ekleme ve 1 değiştirme yapmam gerekti faydalı olacaksa neleri değiştirdiğimi yazabilirim.

**Comment by realsuayip** [comment]
tabii

**Comment by cakmakfurkan** [comment]
Gosu indirilirken "wget: bad address 'github-releases.githubusercontent.com'" hatası geliyordu sertifikalar ile ilgili bir problem vardı sanırım. "ENV GOSU_VERSION 1.12" komutundan önce aşağıdaki komutları eklemem gerekti.

RUN   apk update \                                                                                                                                                                                                                        
 &&   apk add ca-certificates wget \                                                                                                                                                                                                      
 &&   update-ca-certificates  

RUN apk --no-cache add openssl wget

-------------

Gosu paketinin imzası doğrulanırken hkps://keys.openpgp.org sitesi https hatası veriyordu. Siteyi http ye çevirmek zorunda kaldım.

hkp://keys.openpgp.org:80 

----------------

Son olarak setup.sh ve entrypoint.sh çalıştırılırken permission denied hatası alıyordum. Çalıştırma komutlarından önce dosyaların izinlerini değiştirmem gerekti.

RUN chmod +x /usr/src/app/scripts/setup.sh
RUN chmod +x /usr/src/app/scripts/entrypoint.sh

---------------

Dockerfile dosyasının son halini ekliyorum.
[Dockerfile.txt](https://github.com/realsuayip/django-sozluk/files/6564339/Dockerfile.txt)
