### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by iwyz0** [realsuayip/django-sozluk#43]
Merhaba,
docker-compose up -d yapıp çalıştırdıktan sonra kurulum + user açmayı yaptım fakat 8000 portunda çıkış alamıyorum dışarıdan
400 hatası veriyor. Contaner içinden curl atınca yanıt veriyor. 
.env içinde şöyle bir şey var DJANGO_ALLOWED_HOSTS buraya 0.0.0.0 veya ip adresleri yazdım ama sonuç değişmedi nerede yanlış yapıyoruz acaba yardımcı olur musunuz? ellerinize sağlık proje için çok güzel görünüyor

<!doctype html>
<html lang="en">
<head>
  <title>Bad Request (400)</title>
</head>
<body>
  <h1>Bad Request (400)</h1><p></p>
</body>
</html>

**Comment by realsuayip** [comment]
Merhaba allowed hosts değişiminden sonra environment variable'lerin yüklenmesi için tekrar build almanız gerekiyor. Allowed hosts kısmına yazdığınız yerin de siteye erişim yaptığınız host'a eşit olması lazım, bir domain'den falan giriyorsanız mesela domainin adını girmeniz gerek.
