### ISSUE TITLE
":=" Hatası ve Bunun Doğurduğu Entry List Hatası 

### ISSUE THREAD

**Issue by AtaOzalan** [realsuayip/django-sozluk#47]
Merhabalar, 

Kodu deployladığımda aşağıdaki hatayı alıyordum.
![image](https://user-images.githubusercontent.com/45847677/164730691-ddc225f9-ee92-4176-8ce3-c6c98b80fbe2.png)

Bu hatayı düzeltmek için de, ":=" kullanılan yerlerde örneğin bu görselde de gözüken `theme =:request.COOKIES.get("theme","light")) in themes : ` kısmı hatalı gözüktüğü için bunun yerine ; 

`theme = = request.COOKIES.get("theme","light") 
theme in themes: ` olarak değiştirdim. 

Fakat aşağıdaki ekran görüntüsünde görebileceğiniz gibi, aynı başlık içerisine farklı entry girmeye çalıştığımda başka bir url oluşturuluyor. Başlık altında asla yazılar toplanmıyor. 

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/45847677/164730515-8e691c5b-30f4-4162-a887-7396ebbcb2d4.png">

Yardımcı olursanız sevinirim 🙏

**Comment by realsuayip** [comment]
:= operatörü python 3.8 ile geliyor, yanlış python versiyonu kullanıyorsunuz. buradan da anlaşılıyor ki docker kullanmıyorsunuz, lütfen kullanınız
 
:='yi == olarak değiştirmek tamamen bozacaktır bütün logic'i tabii ki.
