### ISSUE TITLE
Logo değişikliği

### ISSUE THREAD

**Issue by EchoBilisim** [realsuayip/django-sozluk#49]
Merhaba ustat logoları (dictionary\static\dictionary\img) klasürden bulup değiştirdim ondan sonra

cd /opt/django-sozluk
docker-compose build --no-cache
docker-compose restart

komutları kullanıyorum ancak eski logo duruyor nerde yanlış yapıyorum?

docker-compose build --no-cache şu komutu kullanırken işlem baya uzun sürüyor ve bazen kırmızı yazılarla uyarı veriyor ondan dolayımı işlemi yapmıyor acaba?

güncelleme ile logo ayarı mail ayarı gibi seçenekleri yönetim panelinden yaparsanız güzel olur diye düşünüyorum öyle bir seçenek mümkünse tabi.

**Comment by realsuayip** [comment]
https://docs.djangoproject.com/en/4.0/ref/contrib/staticfiles/#collectstatic
