### ISSUE TITLE
Profil sayfasinda he zaman bir tane pinned entry gozukuyor

### ISSUE THREAD

**Issue by thrtsksdev** [realsuayip/django-sozluk#56]
Silinebilir.

**Comment by arasdiler** [comment]
Yanlis hatirlamiyosam eger profilde pinli entry yoksa orada top 50 en beğenilen entry'den 1 tane rasgele seçiyordu.

**Comment by thrtsksdev** [comment]
@arasdiler Siz aktif olarak bu projeyi maintain eden ekipten misiniz?

**Comment by arasdiler** [comment]
Hayir. Ufak tefek katkim olmustu diyelim.
