### ISSUE TITLE
Entry & Baslik Gosterimi 

### ISSUE THREAD

**Issue by thrtsksdev** [realsuayip/django-sozluk#60]
Bir suru entry girdim bazilarini admin panelinden olusturdugum channellar'a tasidim ama bir cogunu uncategorized olarak biraktim. Dun uncategorized ve diger chanllera tiklayinca entryleri basliklari gorebiliyordum, bugun baktigimda entryler basliklar uncategorized veya diger kategoriler altinda gosterilmiyor. 

Not: Ana sayfada random olarak entryleri gorebiliyorum ve arama yapinca da yine entryler gozukuyor.

**Comment by arasdiler** [comment]
Kategoriler default olarak son 24 saat icinde gonderilmis entryleri gosterecek sekilde ayarlanmisti. Dolayisiyla 24 saat sonra kayboluyorlar. Ordaki 24 saat kuralini genisletirseniz istediginiz sure kadar o kategorilerdeki entryler gozukecektir.

**Comment by thrtsksdev** [comment]
24 saat ayari sanirim kodda var, nerede oldugunu biliyor musunuz tam olarak?

**Comment by arasdiler** [comment]
dictionary/utils/managers.py 

Burada category bolumu icindeki `**self.day_filter` kismini `entries__date_created__gte` ile degistireceksiniz
![2022-08-18 17 51 31](https://user-images.githubusercontent.com/16455403/185519236-89b445c3-881e-4fd8-bb58-09beb2935f09.jpg)

Burada mesela 120 saat olarak ayarlanmis halini gorebilirsiniz.
![2022-08-18 17 51 38](https://user-images.githubusercontent.com/16455403/185519509-8465d8fd-dbf0-465c-bac9-d077813313e0.jpg)
