### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by thrtsksdev** [realsuayip/django-sozluk#62]
Uye giris yapip Contact sayfasindan iletisime gecince bu admin panelinde Reports bolumunde gozukuyor ama uye olmayan birisi Contact sayfasindan iletisime gecerse bu mesaj Reports bolumunde gosterilmiyor.

**Comment by arasdiler** [comment]
Uye girisi yapmayan bir ziyaretci rapor gondermek isterse emailine giden onay linkine tiklamasi gerekiyor. Tiklamazsa gonderdigi rapor admin panelinde gozukmuyor. Bunu spam filtresi olarak dusunebilirsiniz.

**Comment by thrtsksdev** [comment]
Hocam Skype, Telegram vs var mi sizinle iletisime gecebilir miyim?

**Comment by arasdiler** [comment]
Contributors dosyasinda emailim var ordan iletisime gecebilirsiniz, elimden geldigince yardimci olmaya calisirim.
