### ISSUE TITLE
Pagination is not showing

### ISSUE THREAD

**Issue by jsdev11** [realsuayip/django-sozluk#63]
I've installed the script to play around a little and realized that no matter how many entries I posted, "Show more" and/or pagination did not show up on left sidebar.

I posted 60 + entries and didn't see any pagination or show more, just scrollbar was showing. `graphql` request always returns:

```
hasNext: false
hasOtherPages: false
number: 1
objectList: [60+ objects]
paginator: {pageRange: [1], numPages: 1}
numPages: 1
pageRange: [1]
```

Is this a bug?

**Comment by realsuayip** [comment]
Go to your settings page and check "entries per page", its probably at 100, set it to 10 and you'll see 6+ pages

**Comment by jsdev11** [comment]
I don't know what you mean by "settings page". If you meant Admin dashboard, I don't see anything related to "entries per page" setting. The only place I can see about entries per page is in "apps.py":

```python
# Default options for content object counts
TOPICS_PER_PAGE_DEFAULT = 50  # For guests only
ENTRIES_PER_PAGE_DEFAULT = 10  # For guests only
ENTRIES_PER_PAGE_PROFILE = 15  # Global setting
```

**Comment by jsdev11** [comment]
After several hard refresh & restarting the docker etc, now I can see the pagination for guests.

**Comment by realsuayip** [comment]
these are default values. users can also dynamically change topics per page and entries per page via

example.com/settings

**Comment by jsdev11** [comment]
> these are default values. logged-in users can also dynamically change topics per page and entries per page via
> 
> example.com/settings

Default value for registered uses is 50, not 30.

**Comment by jsdev11** [comment]
> these are default values. logged-in users can also dynamically change topics per page and entries per page via
> 
> example.com/settings

For registered users, topics per page is 50 by default. Can I make the default selected value 30 for registered users? And If possible, can I change the minimum value to a lower one, e.g. 20.

**Comment by realsuayip** [comment]
Yes, see

https://github.com/realsuayip/django-sozluk/blob/4d8432699fde8abaab7981d09298fb65145c1dba/dictionary/models/author.py#L172

**Comment by jsdev11** [comment]
> Yes, see
> 
> https://github.com/realsuayip/django-sozluk/blob/4d8432699fde8abaab7981d09298fb65145c1dba/dictionary/models/author.py#L172

One line above :) Thank you so much!
