### ISSUE TITLE
Show & Update Entry Votes Dynamically

### ISSUE THREAD

**Issue by jsdev11** [realsuayip/django-sozluk#67]
I have two questions.

1. Is it possible to show **total** entry votes value? Is there something like `{{entry.total_vote}}`? For now, I use `entry.vote_rate` but I don't think this is the correct way to show the total votes for an entry. Let's say upvote and downvote rates are 1 and if there is 5 upvotes and 2 downvotes for an entry, I would like to show 3 for the entry.

2. If the answer is yes for the first question, then how can I update this value dynamically without browser refreshing. e.g. when user clicks the upvote or downvote, the entry's total vote value will be updated in the html without any browser refresh.

**Comment by realsuayip** [comment]
This functionality is only available for "replied" entries. You'll have to do some programming to get it to regular entries though.

![image](https://user-images.githubusercontent.com/17948971/192089247-a030db72-0a89-4ac6-b058-05b9d8b272b0.png)
