### ISSUE TITLE
Yönetim Paneline giriş sorunu

### ISSUE THREAD

**Issue by mhmtbsbyndr** [realsuayip/django-sozluk#82]
Öncelikle emegine sağlık, temiz is olmuş.

Lakin Docker ile kurduğum sistemin yönetim paneline giremiyorum. 
http://localhost:8000//admin beni http://localhost:8000/login/ yönlendiriyor ve 
"python manage.py create_generic_user superuser BVT8WnWNF8wJvb4K superuser@example.com --no-input" bilgileri ile giriş yaptigimda ise login sadece tekrarlanmış oluyor.

Sorun hakkında yardimci olabilirsen sevinirim.

**Comment by mhmtbsbyndr** [comment]
docker-compose exec web python manage.py createsuperuser
ile admin oluşturmak istediğimde aldigim hata: 

no configuration file provided: not found

**Comment by yesnt10** [comment]
Merhaba hatayı çözebildiniz mi?

**Comment by mhmtbsbyndr** [comment]
> Merhaba hatayı çözebildiniz mi?

evet sorun cözüldü. tesekkür ederim.
