### ISSUE TITLE
Changing nick does not change the slug

### ISSUE THREAD

**Issue by bcanata** [realsuayip/django-sozluk#88]
Changing the nickname of a user does not change the slug of the user (e.g. https://sozluk.me/author/xxx/).

**Comment by realsuayip** [comment]
although admins can forcibly do it, changing nicks are not allowed on the platform.

since this was the historically accepted that way, parts of the code might not work if this feature is introduced. if a lot of people request it, i might do some research

**Comment by realsuayip** [comment]
now fixed in 1.6.0
