### ISSUE TITLE
sunucu hatası

### ISSUE THREAD

**Issue by yesnt10** [realsuayip/django-sozluk#92]
Merhabalar, projenizi çok beğendik. Elinize sağlık hocam. Ben django.env dosyasında mail ayarı yaptıktan sonra sunucu hatası almaya başladım. Default olanı koyuyorum yine aynı devam ediyor. restart yapıyorum fayda etmiyor. Yardımlarınızı bekliyorum.

sunucu hatası

üzgünüz, talebinizi işlerken beklenmedik bir hata oluştu. bu hata sistem yöneticileri tarafından revize edilmek üzere kenara köşeye kaydedildi. bu arada hiç bir şey olmamış gibi ana sayfaya dönebilirsiniz. eğer bu hatayı sürekli olarak alıyorsanız, lütfen birkaç dakika içinde tekrar deneyin.

**Comment by realsuayip** [comment]
muhtemelen bir configuration hatası var, `DEBUG=False` yaparak hatanın çıktısını alabilirsiniz, o çıktıya bakarak bir şeyler konuşulabilir ancak

**Comment by yesnt10** [comment]
DEBUG=False komutunu nasıl kullanacağımı bilmiyorum, makina değiştirip kurulum yaptım yine 400 hatası veriyor.

**Comment by yesnt10** [comment]
hocam sadece domainde bu hatayı veriyor.

**Comment by realsuayip** [comment]
muhtemelen allowed_hosts ayarın doğru yapılmamış:

https://github.com/realsuayip/django-sozluk/blob/801439d95055e7e3d1ef1295945c2e965279a560/conf/django.env#L3

debug ayarı da aynı dosyada:

https://github.com/realsuayip/django-sozluk/blob/801439d95055e7e3d1ef1295945c2e965279a560/conf/django.env#L1

**Comment by yesnt10** [comment]
> muhtemelen allowed_hosts ayarın doğru yapılmamış:
> 
> https://github.com/realsuayip/django-sozluk/blob/801439d95055e7e3d1ef1295945c2e965279a560/conf/django.env#L3
> 
> debug ayarı da aynı dosyada:
> 
> https://github.com/realsuayip/django-sozluk/blob/801439d95055e7e3d1ef1295945c2e965279a560/conf/django.env#L1

CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000  bu 127 li kısmı domain adresimle değiştiriyorum. bu yüzden mi olmuyor acaba? burası sabit mi kalmalı.

**Comment by realsuayip** [comment]
DEBUG=1 yapmadan ya da loglara bakmadan hangi hatada sıkıntı olduğunu bilemem, muhtemelen birkaç yerde hata vardır diye tahmin ediyorum. bence kendinizi deneyimli bir developer'in ellerine bırakın o sizin için kursun 😁

buradan ilan verebilirsiniz:

https://t.me/django_turkey/36228

**Comment by yesnt10** [comment]
> DEBUG=1 yapmadan ya da loglara bakmadan hangi hatada sıkıntı olduğunu bilemem, muhtemelen birkaç yerde hata vardır diye tahmin ediyorum. bence kendinizi deneyimli bir developer'in ellerine bırakın o sizin için kursun 😁
> 
> buradan ilan verebilirsiniz:
> 
> https://t.me/django_turkey/36228

Hocam daha önce çalıştırmıştım bunu. Şuan tek sorunumuz sadece domain üzerinden girince 400 hatası veriyor. 4.231.125.40 ip adresiyle sorunsuz giriyor. DEBUG=1 yaptım ama site üzerinden herhangi bir değişiklik olmadı. Yardım ederseniz çok sevinirim .
