### ISSUE TITLE
 http://dogasozluk.com:8000/ şeklinde sayfam açılıyor fakat normal şekilde açılmıyor

### ISSUE THREAD

**Issue by cetinkrt** [realsuayip/django-sozluk#94]
Merhabalar

Centos 7 ve plesk panel kullanıyorum 

 http://dogasozluk.com:8000/ şeklinde sayfam açılıyor fakat normal şekilde açılmıyor prodüksyon olarak make yaparsam normal porta 
gelmiyor her şeyi  denedim allowed hosts vs ekledim onda da olmadı ne yapmam gerekiyor?

bir kere oldu 80 kısmı da geldiğinde allowed hosta ekle dedi ekledim yine aynısını diyordu
403 veriyor 400 verdi

502 verdi

**Comment by realsuayip** [comment]
deployment konularında deneyimli bir developer'den destek almanızı rica edeceğim. repo'nun kendisinde deployment engelleyen ile alakalı spesifik bir sorununuz var onunla ilgili detaylı bir issue açabilirsiniz.
