### ISSUE TITLE
Mobil uygulama için api

### ISSUE THREAD

**Issue by bilgehanars** [realsuayip/django-sozluk#99]
Api desteği şu an kısıtlı görünüyor bunu nasıl daha geliştirebiliriz. Siz yapmak istemezseniz yol haritası çizin isterseniz biz halledelim. Elinize emeğinize sağlık proje için

**Comment by realsuayip** [comment]
Selamlar bu projede API desteği olacağını zannetmiyorum. şu an başka bir açık kaynak proje üzerinde çalışıyorum --belki daha gelişmiş bir sözlük projesine dönüşebilecek-- o da yavaş ilerliyor.

eğer API yazmak isterseniz yapman gereken birkaç şey var:

1. GraphQL api için authentication yazmak (şu an session cookie üzerinden gidiyor)
2. Kalan servisleri graphql api'sinde implement etmek. şu anda sitede javascript ile yapılan bazı aksiyonların apisi var. mesela sol frame yüklemek, entry beğenmek, ukte bırakmak vs.

öte yandan REST framework de kullanılıp baştan bir api yazılabilir, ki muhtemelen bu daha kolay olur diye düşünüyorum
